### ISSUE TITLE
The code in `CorruptionCIFAR` class  may be written incorrectly.

### ISSUE THREAD

**Issue by Dyb3438** [BIT-DA/RoTTA#1]
Hi Longhui,
Thanks for your released code of this excellent work! I like this work as it sounds great.

During I was reading the code, and I found one minor error here: https://github.com/BIT-DA/RoTTA/blob/main/core/data/datasets/common_corruption.py#L22

Under my understanding, here may be:

```python
d_id = i_s * len(self.corruptions) + i_c
```
, otherwise, the d_id will have duplicate values. Please check again here.

Yongyi.

**Comment by yuanlonghui** [comment]
Thank you very much for your correction, I will fix this bug.
