### ISSUE TITLE
Question about the size of memory bank.

### ISSUE THREAD

**Issue by vellichorw** [BIT-DA/RoTTA#4]
Hi authors,
**Thanks for your code!** My question is:
Is the size of memory bank always be 64 and keep the same with bsz? 
If so, when the number of categories are large (like CIFAR-100-C or ImageNet-C), _**CSTU**_ would frequently discard previous data (according to _Algorithm1 line5-9_), and is it randomly discard previous data?

**Comment by yuanlonghui** [comment]
Thank you for your attention. For the sake of efficiency and fairness, we chose N = 64.  When the number of categories are large then the size of memory bank, CSTU would discard previous data according to the heuristic score. 
Please refer to the following function, 
https://github.com/BIT-DA/RoTTA/blob/6e0289e1c85cb72efe5b8c73643d35fe31a75f47/core/utils/memory.py#L71

If eligible, the sample with the highest score in the major class would be replaced first.
