### ISSUE TITLE
question about configure_model function

### ISSUE THREAD

**Issue by lhw0772** [BIT-DA/RoTTA#5]
From what I understand, the ROTTA method seems to have a teacher-student structure like the COTTA method, and weight updates should occur not only for batchnorm weights but also for the overall weights. However, in the actual implementation, such as in the configure_model function, only batchnorm weights are updated. Am I correct in understanding it according to the implementation?

**Comment by yuanlonghui** [comment]
When we update the student model, only the weights in BN are updated (actually RBN in our method), which is normal in TTA for stable adaptation. When update the teacher model, due to only BN layers in student model have been updated, so we only update the BN layers in teacher model.
