### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by leiouultraman** [BIT-DA/RoTTA#7]
作者你好，我下载好预训练模型之后，重新运行代码还是会自动下载预训练模型，然后导致代码运行失败，请问这是什么原因造成的呢，以下是我文件存放的形式
![截图 2024-03-28 18-17-32](https://github.com/BIT-DA/RoTTA/assets/137867729/0db2a3bd-d132-45b5-be7b-9e6c5a71354b)

**Comment by yuanlonghui** [comment]
代码里面用到的两个checkpoint存放方式如下：
![image](https://github.com/BIT-DA/RoTTA/assets/68118044/c620c407-6ada-4ae1-99f6-15dd21df2722)
分别对应着 MODEL.ARCH 的值为 Standard （cifar10数据集） 和 Hendrycks2020AugMix_ResNeXt （cifar100数据集）

如果你换了网络结构（看上面的图片好像是这么回事），需要修改对应的 MODEL.ARCH 参数 （在RoTTA/configs/dataset/cifar10.yaml和RoTTA/configs/dataset/cifar100.yaml中）
具体做法可以是新建一个 yaml 配置文件 （推荐），或者直接修改对应存在的 yaml 文件，或者在命令行最后添加
```bash
python ptta.py \
      -acfg configs/adapter/rotta.yaml \
      -dcfg configs/dataset/cifar10.yaml \
      OUTPUT_DIR RoTTA/cifar10 \
      MODEL.ARCH your_arch
```
MODEL.ARCH 的对应关系需参照 https://github.com/RobustBench/robustbench 的 Model Zoo。

**Comment by leiouultraman** [comment]
https://github.com/RobustBench/robustbench/issues/174#issue-2177550793   ，这个回答里面有解决措施，非常感谢作者的回复
